.PHONY: clean All

All:
	@echo "----------Building project:[ 12-arrays - Debug ]----------"
	@cd "12-arrays" && "$(MAKE)" -f  "12-arrays.mk"
clean:
	@echo "----------Cleaning project:[ 12-arrays - Debug ]----------"
	@cd "12-arrays" && "$(MAKE)" -f  "12-arrays.mk" clean
